### ISSUE TITLE
supports git-upload-pack?

### ISSUE THREAD

**Issue by swordow** [jasonwhite/rudolfs#35]
When git lfs push --all, the first request is something like this:
api/org/project/info/refs?service=git-upload-pack - 404 Not Found

**Comment by jasonwhite** [comment]
That's not part of the LFS protocol AFAIK. That looks like it is part of the Git protocol itself: https://git-scm.com/docs/http-protocol/2.29.0#_smart_clients

I think the correct response is indeed a 404 error since the LFS client shouldn't be sending such a request. I suspect something is misconfigured in the repository.

**Comment by swordow** [comment]
Sorry. I misconfigured the lfs server with git server backend.
