### ISSUE TITLE
Downloading blobs programmatically

### ISSUE THREAD

**Issue by muliyul** [jasonwhite/rudolfs#39]
Is there any client compatible with rudolfs? I'm using Kotlin and conveniently tried to use [this library](https://github.com/bozaro/git-lfs-java) (specifically the client and pointer modules) but got 404 for missing endpoint? (`http://localhost:8081/api/some-org/some-repo/info/lfs/objects/batch`)

perhaps batch is not supported?

My use case:
S3 to contain files versioned by git using LFS (rudolfs), then at runtime access (download) different versions of these files (while performing relatively fast checkouts in the local FS).

**Comment by jasonwhite** [comment]
The Git LFS client is compatible, so the batch API is definitely supported (otherwise Rudolfs would be rather useless).

The endpoint in your example should be:
```
http://localhost:8081/api/some-org/some-repo/objects/batch
```
(No `/info/lfs`)

The confusion may have been caused by [GitHub's docs of the batch API](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md). They give `https://git-server.com/foo/bar.git/info/lfs/objects/batch` as an example endpoint, but that's because the LFS server's base URL is at `https://git-server.com/foo/bar.git/info/lfs`. The base URL for Rudolfs doesn't have the `/info/lfs` suffix.

**Comment by muliyul** [comment]
That is quite interesting because the library appends this path (I haven't checked but this may be part of the spec). See [here](https://github.com/bozaro/git-lfs-java/blob/5e52f6bcbec7a6ea5df0de5dccd0e8b8c999f832/gitlfs-client/src/main/kotlin/ru/bozaro/gitlfs/client/AuthHelper.kt#L42)

**Comment by jasonwhite** [comment]
We could support the `/info/lfs` suffix as well, but I think this is really a bug in https://github.com/bozaro/git-lfs-java.
